FinancialPlannerApplication/FinancialPlannerApplication/Models/Budget.cs
using System;
using System.Collections.Generic;

namespace FinancialPlannerApplication.Models
{
    public class Budget
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public virtual ICollection<BudgetItem> BudgetItems { get; set; }
        public string Username { get; set; }
    }
}

FinancialPlannerApplication/FinancialPlannerApplication/Models/ViewModels/BudgetDetailsViewModel.cs
using System.Collections.Generic;

namespace FinancialPlannerApplication.Models.ViewModels
{
    public class BudgetDetailsViewModel
    {
        public IList<BudgetItemViewModel> BudgetItems { get; set; } 
        public BudgetViewModel Budget { get; set; }
    }
}

FinancialPlannerApplication/FinancialPlannerApplication/Models/ViewModels/BudgetViewModel.cs
using System;
using System.Collections.Generic;

namespace FinancialPlannerApplication.Models.ViewModels
{
    public class BudgetViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public virtual ICollection<BudgetDetailsViewModel> BudgetItems { get; set; } 
    }
}

FinancialPlannerApplication/FinancialPlannerApplication/Models/ViewModels/EditBudgetItemViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinancialPlannerApplication.Models.ViewModels
{
    public class EditBudgetItemViewModel
    {
        public int BudgetItemId { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Amount is required")]
        public decimal Amount { get; set; }
        [Required(ErrorMessage = "Must select a budget")]
        public int SelectedBudgetId { get; set; }
        public IList<BudgetViewModel> Budgets { get; set; }
    }
}

FinancialPlannerApplication/FinancialPlannerApplication/Models/ViewModels/EditBudgetViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FinancialPlannerApplication.Models.ViewModels
{
    public class EditBudgetViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Start date is required")]
        public DateTime StartDate { get; set; }
        [Required(ErrorMessage = "End date is required")]
        public DateTime EndDate { get; set; }
    }
}

FinancialPlannerApplication/FinancialPlannerApplication/Controllers/BudgetController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using FinancialPlannerApplication.Models;
using FinancialPlannerApplication.Models.DataAccess;
using FinancialPlannerApplication.Models.Services;
using FinancialPlannerApplication.Models.ViewModels;

namespace FinancialPlannerApplication.Controllers
{
    [Authorize]
    public class BudgetController : Controller
    {
        private readonly IFinancialPlannerRepository FinancialPlannerRepository;
        private readonly IBudgetService BudgetService;
        private readonly ISetViewModelsService SetViewModelsService;
        private const int NotSelected = -1;

        public BudgetController(IFinancialPlannerRepository financialPlannerRepository, IBudgetService budgetService,
            ISetViewModelsService setViewModelsService)
        {
            FinancialPlannerRepository = financialPlannerRepository;
            BudgetService = budgetService;
            SetViewModelsService = setViewModelsService;
        }

        public ActionResult Index(int budgetId = 0, int budgetItemId = 0)
        {
            var username = User.Identity.Name;
            var vm = BudgetService.MapBudgetIndexViewModel(username);

            vm.SelectedBudgetId = budgetId;
            vm.SelectedBudgetItemId = budgetItemId;
            
            return View(vm);
        }

        public ActionResult AddBudget()
        {
            ViewBag.Title = "Add Budget";

            return PartialView("EditBudget");
        }

        [HttpPost]
        public ActionResult AddBudget(EditBudgetViewModel vm)
        {
            ViewBag.Title = "Add Budget";

            ModelState.Remove("Id");
            if (!ModelState.IsValid)
            {
                return ReturnViewWithDateError(vm);
            }

            ViewBag.Title = "Edit Budget";
            if (vm.Id == 0)
            {
                return AddBudgetReturnEditBudgetView(vm);
            }

            EditBudget(vm);

            return PartialView("EditBudget", vm);
        }

        private ActionResult AddBudgetReturnEditBudgetView(EditBudgetViewModel vm)
        {
            var username = User.Identity.Name;
            var budget = BudgetService.AddBudget(vm, username);

            ModelState.Clear();
            vm.Id = budget.Id;

            return PartialView("EditBudget", vm);
        }

        private ActionResult ReturnViewWithDateError(EditBudgetViewModel vm)
        {
            if (vm.EndDate < vm.StartDate)
            {
                ModelState.AddModelError("StartEnd", "End Date must be later than Start Date");
            }

            return PartialView("EditBudget", vm);
        }

        [HttpPost]
        public ActionResult EditBudget(EditBudgetViewModel vm)
        {
            ViewBag.Title = "Edit Budget";

            if (!ModelState.IsValid)
                return ReturnViewWithDateError(vm);             

            var saved = BudgetService.EditBudget(vm);

            if (!saved)
                return View("Error");

            return PartialView("EditBudget", vm);
        }

        public ActionResult AddBudgetItem()
        {
            var username = User.Identity.Name;
            var vm = BudgetService.MapEditBudgetItemViewModelForAdd(username);

            ViewBag.Title = "Add Budget Item";

            return PartialView("EditBudgetItem", vm);
        }

        [HttpPost]
        public ActionResult AddBudgetItem(EditBudgetItemViewModel vm, bool isDone)
        {
            ViewBag.Title = "Add Budget Item";

            var budgets = FinancialPlannerRepository.GetBudgets().Where(m => m.Username == User.Identity.Name);
            vm.Budgets = SetViewModelsService.SetBudgetViewModels(budgets);

            if (vm.SelectedBudgetId == NotSelected)
                ModelState.AddModelError("SelectedBudgetId", "Budget must be selected");

            if (!ModelState.IsValid)
                return PartialView("EditBudgetItem", vm);

            ViewBag.Title = "Edit Budget Item";

            var budgetItem = new BudgetItem();
            if (vm.BudgetItemId == 0)
            {
                budgetItem = BudgetService.AddBudgetItem(vm);
                ModelState.Remove("BudgetItemId");
                vm.BudgetItemId = budgetItem.Id;

                return PartialView("EditBudgetItem", vm);
            }

            return isDone ? RedirectToAction("Index", new {budgetId = budgetItem.BudgetId, budgetItemId = budgetItem.Id}) : EditBudgetItem(vm, false);
        }

        [HttpPost]
        public ActionResult EditBudgetItem(EditBudgetItemViewModel vm, bool isDone)
        {
            ViewBag.Title = "Edit Budget Item";

            var budgets = FinancialPlannerRepository.GetBudgets().Where(m => m.Username == User.Identity.Name);
            vm.Budgets = SetViewModelsService.SetBudgetViewModels(budgets);

            if (vm.SelectedBudgetId == NotSelected)
            {
                ModelState.AddModelError("SelectedBudgetId", "Budget must be selected");
                return PartialView("EditBudgetItem", vm);
            }

            var saved = BudgetService.EditBudgetItem(vm);

            if (!saved)
                return View("Error");

            if (isDone)
                return RedirectToAction("Index", new { budgetId = vm.SelectedBudgetId, budgetItemId = vm.BudgetItemId });

            return PartialView("EditBudgetItem", vm);
        }

        public ActionResult AddBudgetItemTransaction(int id)
        {
            var username = User.Identity.Name;

            var vm = BudgetService.MapEditBudgetItemTransactionViewModelForAdd(username, id);

            if (vm == null)
                return View("Error");

            ViewBag.Title = "Add Budget Item Transaction";

            return PartialView("EditBudgetItemTransaction", vm);
        }

        public ActionResult LoadBudgetDetails(int id)
        {
            var vm = BudgetService.MapBudgetDetailsViewModel(id);

            return PartialView("BudgetDetails", vm);
        }

        public ActionResult LoadBudgetItemTransactions(int id)
        {
            var vm = BudgetService.MapBudgetItemTransactionViewModel(id);

            return PartialView("BudgetItemTransactions", vm);
        }

        public ActionResult EditBudget(int id)
        {
            var vm = BudgetService.MapEditBudgetViewModel(id);

            if (vm == null)
                return View("Error");

            ViewBag.Title = "Edit Budget";

            return PartialView(vm);
        }

        public ActionResult EditBudgetItem(int id)
        {
            var username = User.Identity.Name;
            var vm = BudgetService.MapEditBudgetItemViewModel(id, username);

            if (vm == null)
                return View("Error");

            ViewBag.Title = "Edit Budget Item";

            return PartialView(vm);
        }

        public ActionResult EditBudgetItemTransaction(int id)
        {
            var username = User.Identity.Name;

            var vm = BudgetService.MapEditBudgetItemTransactionViewModelForEdit(id, username);

            if (vm == null)
                return View("Error");

            ViewBag.Title = "Edit Budget Item Transaction";

            return PartialView(vm);
        }

        [HttpPost]
        public ActionResult AddBudgetItemTransaction(EditBudgetItemTransactionViewModel vm, bool isDone)
        {
            ViewBag.Title = "Add Budget Item Transaction";
            var username = User.Identity.Name;

            if (vm.FindingBudgetItems)
            {
                return FindBudgetItemsReturnEditTransactionView(ref vm, username);
            }

            if (vm.BudgetItemTransactionId == 0)
            {
                if (vm.SelectedBudgetId == NotSelected)
                {
                    ModelState.AddModelError("SelectedBudgetId", "A budget must be selected");
                }

                if (!ModelState.IsValid)
                {
                    vm = BudgetService.MapEditBudgetItemTransactionViewModelChangeBudget(username, vm);
                    return View("EditBudgetItemTransaction", vm);
                }

                ViewBag.Title = "Edit Budget Item Transaction";

                var budgetItemTransaction = BudgetService.AddBudgetItemTransaction(vm);

                ModelState.Remove("BudgetItemTransactionId");

                vm.BudgetItemTransactionId = budgetItemTransaction.Id;

                var budgetItemSaved = BudgetService.EditBudgetItemForAdd(vm);

                if (!budgetItemSaved)
                    return View("Error");

                if (vm.SelectedAccountId != -1)
                {
                    var account = FinancialPlannerRepository.GetAccounts().FirstOrDefault(m => m.Id == vm.SelectedAccountId);

                    if (account == null)
                        return View("Error");

                    EditAccountAmountAndTransactionBalances(vm, account);
                }

                EditExpenseBalance(vm, budgetItemTransaction);

                vm = BudgetService.MapEditBudgetItemTransactionViewModelChangeBudget(username, vm);

                if (isDone)
                    return RedirectToAction("Index",
                        new {budgetId = vm.SelectedBudgetId, budgetItemId = vm.SelectedBudgetItemId});

                return PartialView("EditBudgetItemTransaction", vm);
            }

            ViewBag.Title = "Edit Budget Transaction";

            return isDone ? RedirectToAction("Index", new { budgetId = vm.SelectedBudgetId, budgetItemId = vm.SelectedBudgetItemId }) : EditBudgetItemTransaction(vm, false);
        }

        private void EditExpenseBalance(EditBudgetItemTransactionViewModel vm, Transaction budgetItemTransaction)
        {
            var expense = FinancialPlannerRepository.GetExpenses().FirstOrDefault(m => m.Id == vm.SelectedExpenseId);

            if (expense != null)
            {

FinancialPlannerApplication/FinancialPlannerApplication/Views/Budget/BudgetDetails.cshtml
@model FinancialPlannerApplication.Models.ViewModels.BudgetDetailsViewModel

<div id="budgetItemsView">
    <h3>
        @Model.Budget.Name
        <button id="addBudgetItemButton" class="btn btn-primary" type="button" data-request-url="@Url.Action("AddBudgetItem", "Budget")">Add</button>
    </h3>

    <table class="table table-hover" id="budgetItems">
        <thead>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>Balance</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.BudgetItems)
            {
                <tr class="budgetItemRow" id="@item.Id" data-request-url="@Url.Action("LoadBudgetItemTransactions")">
                    <td>@item.Name</td>
                    <td>@item.Amount.ToString("F")</td>
                    <td>@item.Balance.ToString("F")</td>
                    <td><button type="button" class="btn btn-primary editBudgetItem" data-request-url="@Url.Action("EditBudgetItem", "Budget")">Edit</button></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div id="budgetItemTransactions"></div>

<div id="editBudgetItem"></div>

<div id="addBudgetItem"></div>

<script src="~/Scripts/account-budgetdetails.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/Budget/BudgetItemTransactions.cshtml
@model FinancialPlannerApplication.Models.ViewModels.BudgetItemTransactionViewModel

<div id="budgetItemTransactionsSection">
    @Html.HiddenFor(m => m.BudgetItemId)
    <h4>
        Transactions
        <button id="addBudgetItemTransactionButton" class="btn btn-primary" type="button" data-request-url="@Url.Action("AddBudgetItemTransaction", "Budget")">Add</button>
    </h4>

    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Payment Date</th>
            <th>Amount</th>
            <th>&nbsp;</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var transaction in Model.BudgetItemTransactions)
        {
            <tr>
                <td>@transaction.Name</td>
                @if (transaction.IsWithdrawal)
                {
                    <td>Withdrawal</td>
                }
                else
                {
                    <td>Deposit</td>
                }
                <td>@transaction.PaymentDate.ToShortDateString()</td>
                <td>@transaction.Amount</td>
                <td><button type="button" class="btn btn-primary editBudgetItemTransaction" id="@transaction.Id" data-request-url="@Url.Action("EditBudgetItemTransaction", "Budget")">Edit</button></td>
            </tr>
        }
        <tr>
            <td colspan="2"></td>
            <td>Total:</td>
            <td colspan="2">@Model.TransactionTotal</td>
        </tr>
        </tbody>
    </table>
</div>   

<div id="editBudgetItemTransaction"></div>

<div id="addBudgetItemTransaction"></div>

<script src="~/Scripts/budget-budgetItemTransactions.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/Budget/EditBudget.cshtml
@model FinancialPlannerApplication.Models.ViewModels.EditBudgetViewModel

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <div class="form-horizontal">
            @using (Html.BeginForm(null, null, FormMethod.Post, new{@id="editBudgetForm"}))
            {
                @Html.HiddenFor(m => m.Id)
                @Html.ValidationSummary(true)
                <div class="form-group">
                    <label class="col-md-2 control-label">Name</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new {@class = "form-control budgetName"})
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Start Date</label>
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.StartDate, "Date", new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.StartDate)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">End Date</label>
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.EndDate, "Date", new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.EndDate)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" id="saveBudgetButton" class="btn btn-primary">Save</button>
                        @*<button type="button" class="btn btn-primary">Done</button>*@
                        @Html.ActionLink("Done", "Index", null, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Cancel", "Index", null, new {@class = "btn btn-primary"})
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/Scripts/datepicker-initialize.js"></script>

<script src="~/Scripts/budget-edit.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/Budget/EditBudgetItem.cshtml
@using FinancialPlannerApplication.Extensions
@model FinancialPlannerApplication.Models.ViewModels.EditBudgetItemViewModel

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <div class="form-horizontal">
            @using (Html.BeginForm(null, null, FormMethod.Post, new{@id="editBudgetItemForm"}))
            {
                @Html.HiddenFor(m => m.BudgetItemId)
                @Html.ValidationSummary(true)
                <div class="form-group">
                    <label class="col-md-2 control-label">Name</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new {@class = "form-control budgetItemFormItem"})
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Amount</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Amount, new { @class = "form-control budgetItemFormItem" })
                        @Html.ValidationMessageFor(m => m.Amount)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Budget</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.SelectedBudgetId, Model.Budgets.ToSelectList(m => m.Name, m => m.Id, Model.Budgets.Where(m => m.Id == Model.SelectedBudgetId), "--Select One--"), new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.SelectedBudgetId)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-primary" id="saveBudgetItemButton">Save</button>
                        <button type="button" class="btn btn-primary" id="doneEditBudgetItem">Done</button>
                        @*@Html.ActionLink("Done", "Index", null, new { @class = "btn btn-primary" })*@
                        @Html.ActionLink("Cancel", "Index", null, new {@class = "btn btn-primary"})
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/Scripts/budgetItem-edit.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/Budget/EditBudgetItemTransaction.cshtml
@using FinancialPlannerApplication.Extensions
@model FinancialPlannerApplication.Models.ViewModels.EditBudgetItemTransactionViewModel

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <div class="form-horizontal">
            @using (Html.BeginForm(null, null, FormMethod.Post, new{@id = "editBudgetTransactionForm"}))
            {
                @Html.HiddenFor(m => m.BudgetItemTransactionId)
                @Html.HiddenFor(m => m.OldAccountId)
                @Html.HiddenFor(m => m.WasWithdrawal)
                @Html.HiddenFor(m => m.OldAmount)
                @Html.HiddenFor(m => m.FindingBudgetItems)
                @Html.ValidationSummary(true)
                <div class="form-group">
                    <label class="col-md-2 control-label">Name</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control budgetItemFormItemTransaction" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Amount</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Amount, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.Amount)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Payment Date</label>
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.PaymentDate, "Date", new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.PaymentDate)
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label">Budget</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.SelectedBudgetId, Model.Budgets.ToSelectList(m => m.Name, m => m.Id, Model.Budgets.Where(m => m.Id == Model.SelectedBudgetId), "--Select One--"), new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.SelectedBudgetId)
                    </div>
                </div>
                if (Model.SelectedBudgetId > 0)
                {
                     <div class="form-group">
                         <label class="col-md-2 control-label">Budget Item</label>
                         <div class="col-md-10">
                             @Html.DropDownListFor(m => m.SelectedBudgetItemId, Model.BudgetItems.ToSelectList(m => m.Name, m => m.Id, Model.BudgetItems.Where(m => m.Id == Model.SelectedBudgetItemId), "--Select One--"), new {@class = "form-control"})
                             @Html.ValidationMessageFor(m => m.SelectedBudgetItemId)
                         </div>
                     </div>
                 }
                <div class="form-group">
                    <label class="col-md-2 control-label">Account</label>
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.SelectedAccountId, Model.Accounts.ToSelectList(m => m.Name, m => m.Id, Model.Accounts.Where(m => m.Id == Model.SelectedAccountId), "--Select One--"), new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.SelectedAccountId)
                    </div>
                </div>
                if (Model.Expenses != null && Model.Expenses.Any())
                {
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Expense
                        </label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(m => m.SelectedExpenseId, Model.Expenses.ToSelectList(m => m.Name, m => m.Id, Model.Expenses.Where(m => m.Id == Model.SelectedExpenseId), "--Select One--"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.SelectedExpenseId)
                        </div>
                    </div>
                }
                <div class="form-group">
                    <div class="col-md-12">
                        <label class="col-md-2 control-label">Withdrawal</label>
                        <div class="col-md-2">
                            @Html.RadioButtonFor(m => m.IsWithdrawal, true)
                        </div>
                        <label class="col-md-2 control-label">Deposit</label>
                        <div class="col-md-4">
                            @Html.RadioButtonFor(m => m.IsWithdrawal, false)
                        </div>
                        @Html.ValidationMessageFor(m => m.IsWithdrawal)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-primary" id="saveBudgetItemTransactionButton">Save</button>
                        <button type="button" class="btn btn-primary" id="doneEditBudgetTransaction">Done</button>
                        @*@Html.ActionLink("Done", "Index", null, new { @class = "btn btn-primary" })*@
                        @Html.ActionLink("Cancel", "Index", null, new {@class = "btn btn-primary"})
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/Scripts/datepicker-initialize.js"></script>
<script src="~/Scripts/budgetItemTransaction-edit.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/Budget/Index.cshtml
@model FinancialPlannerApplication.Models.ViewModels.BudgetIndexViewModel

@{
    ViewBag.Title = "Budgets";
}

@Html.HiddenFor(m => m.SelectedBudgetId)
@Html.HiddenFor(m => m.SelectedBudgetItemId)

<div id="budgetIndex">
    <h2>
        Budgets
        <button type="button" class="btn btn-primary" id="addBudgetButton" data-request-url="@Url.Action("AddBudget")">Add</button>
    </h2>

    <table class="table table-hover" id="budgetsTable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var budget in Model.Budgets)
            {
                <tr class="budgetRow" id="@budget.Id" data-request-url="@Url.Action("LoadBudgetDetails")">
                    <td>@budget.Name</td>
                    <td>@budget.StartDate</td>
                    <td>@budget.EndDate</td>
                    <td><button type="button" class="btn btn-primary editBudget" data-request-url="@Url.Action("EditBudget")">Edit</button></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div id="budgetDetails"></div>

<div id="editBudget"></div>

<div id="addBudget"></div>

@section scripts {
   <script src="~/Scripts/budget-index.js"></script>
}