FinancialPlannerApplication/FinancialPlannerApplication/Models/ViewModels/EditAccountViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FinancialPlannerApplication.Models.ViewModels
{
    public class EditAccountViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Amount is required")]
        public decimal Amount { get; set; }
        public string UserName { get; set; }
    }
}

FinancialPlannerApplication/FinancialPlannerApplication/Controllers/FinancialPlannerAccountController.cs
using System.Linq;
using System.Web.Mvc;
using FinancialPlannerApplication.Models;
using FinancialPlannerApplication.Models.DataAccess;
using FinancialPlannerApplication.Models.Services;
using FinancialPlannerApplication.Models.ViewModels;

namespace FinancialPlannerApplication.Controllers
{
    [Authorize]
    public class FinancialPlannerAccountController : Controller
    {
        private readonly IFinancialPlannerRepository FinancialPlannerRepository;
        private readonly IFinancialPlannerAccountService FinancialPlannerAccountService;
        private const int NotSelected = -1;

        public FinancialPlannerAccountController(IFinancialPlannerRepository financialPlannerRepository,
            IFinancialPlannerAccountService financialPlannerAccountService)
        {
            FinancialPlannerRepository = financialPlannerRepository;
            FinancialPlannerAccountService = financialPlannerAccountService;
        }

        public ActionResult Index(int accountId = 0)
        {
            var vm = FinancialPlannerAccountService.MapAccountIndexViewModel(User.Identity.Name);

            vm.SelectedAccountId = accountId;

            return View(vm);
        }

        public ActionResult AddAccount()
        {
            return MapEditAccountViewModel();
        }

        [HttpPost]
        public ActionResult AddAccount(EditAccountViewModel vm)
        {
            ViewBag.Title = "Add Account";

            if (!ModelState.IsValid)
                return PartialView("EditAccount", vm);

            if (vm.Id == 0)
            {
                ModelState.Remove("Id");
                var account = FinancialPlannerAccountService.AddAccount(User.Identity.Name, vm);
                vm.Id = account.Id;

                ViewBag.Title = "Edit Account";

                return PartialView("EditAccount", vm);
            }
            
            
            return EditAccount(vm);
        }

        public ActionResult AddAccountTransaction()
        {
            var username = User.Identity.Name;
            var vm = FinancialPlannerAccountService.MapEditTransactionViewModel(username);

            ViewBag.Title = "Add Account Transaction";

            return PartialView("EditTransaction", vm);
        }

        public ActionResult EditAccount(int id)
        {
            return MapEditAccountViewModel(id);
        }

        [HttpPost]
        public ActionResult EditAccount(EditAccountViewModel vm)
        {
            var username = User.Identity.Name;

            var saved = FinancialPlannerAccountService.EditAccount(vm, username);

            if (!saved)
                return View("Error");

            ViewBag.Title = "Edit Account";

            return PartialView("EditAccount", vm);
        }

        public ActionResult LoadAccountTransactions(int id)
        {
            var vm = FinancialPlannerAccountService.MapAccountTransactionsViewModel(id);

            return PartialView("AccountTransactions", vm);
        }

        public ActionResult EditTransaction(int id, int accountId)
        {
            var username = User.Identity.Name;
            var vm = FinancialPlannerAccountService.MapEditTransactionViewModelForEdit(id, accountId, username);

            if (vm == null)
                return View("Error");

            ViewBag.Title = "Edit Transaction";

            return PartialView("EditTransaction", vm);
        }

        public ActionResult AddTransaction(int id)
        {
            var username = User.Identity.Name;
            var vm = FinancialPlannerAccountService.MapEditTransactionViewModelForAdd(id, username);

            if (vm == null)
                return View("Error");

            ViewBag.Title = "Add Transaction";

            return PartialView("EditTransaction", vm);
        }

        [HttpPost]
        public ActionResult AddTransaction(EditTransactionViewModel vm, bool isDone = false)
        {
            ViewBag.Title = "Add Transaction";

            var transaction = new Transaction();

            if (vm.FindingBudgetItems)
            {
                return FindBudgetItemsAndReturn(vm);
            }

            AddNoAccountSelectedError(vm);

            if (!ModelState.IsValid)
            {
                return MapEditTransactionViewModelAndReturn(vm);
            }

            if (vm.AccountTransactionId == 0)
            {
                var account = FinancialPlannerRepository.GetAccounts().FirstOrDefault(m => m.Id == vm.SelectedAccountId);

                if (account == null)
                    return View("Error");

                transaction = AdjustBalancesForTransaction(vm, account);

                ModelState.Remove("AccountTransactionId");
                FinancialPlannerAccountService.MapEditTransactionViewModel(vm, User.Identity.Name);
                vm.AccountTransactionId = transaction.Id;

                ViewBag.Title = "Edit Transaction";

                return PartialView("EditTransaction", vm);
            }

            return isDone ? RedirectToAction("Index", new { accountId = transaction.AccountId }) : EditTransaction(vm);
        }

        [HttpPost]
        public ActionResult AddTransactionDone(EditTransactionViewModel vm)
        {
            ViewBag.Title = "Add Transaction";

            var transaction = new Transaction();

            if (vm.FindingBudgetItems)
            {
                return FindBudgetItemsAndReturn(vm);
            }

            AddNoAccountSelectedError(vm);

            if (!ModelState.IsValid)
            {
                return MapEditTransactionViewModelAndReturn(vm);
            }

            if (vm.AccountTransactionId == 0)
            {
                var account = FinancialPlannerRepository.GetAccounts().FirstOrDefault(m => m.Id == vm.SelectedAccountId);

                if (account == null)
                    return View("Error");

                transaction = AdjustBalancesForTransaction(vm, account);

                ModelState.Remove("AccountTransactionId");
                FinancialPlannerAccountService.MapEditTransactionViewModel(vm, User.Identity.Name);
                vm.AccountTransactionId = transaction.Id;

                //FinancialPlannerAccountService.AddTransaction(account, vm);

                ViewBag.Title = "Edit Transaction";

                //return PartialView("EditTransaction", vm);
            }


            return RedirectToAction("Index", new{accountId = transaction.AccountId});
        }

        private Transaction AdjustBalancesForTransaction(EditTransactionViewModel vm, Account account)
        {
            FinancialPlannerAccountService.AdjustAccountBalance(account, vm);

            var transaction = FinancialPlannerAccountService.AddTransaction(account, vm);

            FinancialPlannerAccountService.AdjustTransactionBalances(account, vm);

            if (vm.SelectedBudgetItemId != null && vm.SelectedBudgetItemId > 0)
            {
                AdjustBudgetItemBalance(vm);
            }

            var expense = FinancialPlannerRepository.GetExpenses().FirstOrDefault(m => m.Id == vm.SelectedExpenseId);

            if (expense != null)
            {
                FinancialPlannerAccountService.AdjustExpenseBalance(expense, transaction);
            }
            return transaction;
        }

        private void AdjustBudgetItemBalance(EditTransactionViewModel vm)
        {
            var budgetItem =
                FinancialPlannerRepository.GetBudgetItems().FirstOrDefault(m => m.Id == vm.SelectedBudgetItemId);

            if (budgetItem != null)
                FinancialPlannerAccountService.AdjustBudgetItemBalance(budgetItem, vm);
        }

        private ActionResult MapEditTransactionViewModelAndReturn(EditTransactionViewModel vm)
        {
            FinancialPlannerAccountService.MapEditTransactionViewModel(vm, User.Identity.Name);

            return PartialView("EditTransaction", vm);
        }

        private void AddNoAccountSelectedError(EditTransactionViewModel vm)
        {
            if (vm.SelectedAccountId == NotSelected)
            {
                ModelState.AddModelError("SelectedAccountId", "An account must be selected");
            }
        }

        private ActionResult FindBudgetItemsAndReturn(EditTransactionViewModel vm)
        {
            FinancialPlannerAccountService.MapEditTransactionViewModel(vm, User.Identity.Name);

            ModelState.Remove("FindingBudgetItems");
            vm.FindingBudgetItems = false;

            return PartialView("EditTransaction", vm);
        }

        [HttpPost]
        public ActionResult EditTransaction(EditTransactionViewModel vm, bool isDone = false)
        {
            @ViewBag.Title = "Edit Transaction";

            if (vm.FindingBudgetItems)
            {
                return FindBudgetItemsAndReturn(vm);
            }

            AddNoAccountSelectedError(vm);

            if (!ModelState.IsValid)
            {
                return MapEditTransactionViewModelAndReturn(vm);
            }

            var account = FinancialPlannerRepository.GetAccounts().FirstOrDefault(m => m.Id == vm.SelectedAccountId);

            var transaction = FinancialPlannerRepository.GetTransactions().FirstOrDefault(m => m.Id == vm.AccountTransactionId);
            
            if (transaction == null)
                return View("Error");

            //think about consolidating this
            var oldBudgetItemId = transaction.BudgetItemId;
            var oldExpenseId = transaction.ExpenseId;
            transaction.AccountId = vm.SelectedAccountId;

            FinancialPlannerAccountService.EditTransaction(vm);

            FinancialPlannerAccountService.AdjustOldBudgetItemBalance(oldBudgetItemId);

            if (oldBudgetItemId != vm.SelectedBudgetItemId)
            {
                FinancialPlannerAccountService.AdjustNewBudgetItemBalance(vm);
            }

            AdjustAccountTransactionBalances(vm, account);

FinancialPlannerApplication/FinancialPlannerApplication/Views/FinancialPlannerAccount/AccountTransactions.cshtml
@model FinancialPlannerApplication.Models.ViewModels.AccountTransactionsViewModel

<div id="accountTransactionsView">
    <h4>
        Transactions
        <button type="button" class="btn btn-primary" id="addAccountTransactionButton" data-request-url="@Url.Action("AddTransaction", "FinancialPlannerAccount")">Add</button>
    </h4>

    <table class="table" id="accountTransactionsTable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Payment Date</th>
                <th>Amount</th>
                <th>Balance</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var transaction in Model.Transactions)
            {
                <tr>
                    <td>@transaction.Name</td>
                    <td>
                        @if (transaction.IsWithdrawal)
                        {
                            <text>Withdrawal</text>
                        }
                        else
                        {
                            <text>Deposit</text>
                        }
                    </td>
                    <td>@transaction.PaymentDate.ToShortDateString()</td>
                    <td>@transaction.Amount</td>
                    <td>@transaction.Balance</td>
                    <td>
                        <button class="btn btn-primary transactionRow" id="@transaction.Id" type="button" data-request-url="@Url.Action("EditTransaction", "FinancialPlannerAccount")">Edit</button>
                    </td>
                </tr>
            }
            <tr>
                <td colspan="2"></td>
                <td>Total:</td>
                <td colspan="3">@Model.TransactionTotal</td>
            </tr>
        </tbody>
    </table> 
</div>

<div id="editTransaction"></div>

<div id="addAccountTransaction"></div>

<script src="~/Scripts/shared-accountTransactions.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/FinancialPlannerAccount/EditAccount.cshtml
@using Glimpse.Mvc.AlternateType
@model FinancialPlannerApplication.Models.ViewModels.EditAccountViewModel

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <div class="form-horizontal">
            @using (Html.BeginForm(null, null, FormMethod.Post, new{@id="editAccountForm"}))
            {
                @Html.HiddenFor(m => m.Id)
                @Html.ValidationSummary(true)
                <div class="form-group">
                    <label class="col-md-2 control-label">Name</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Amount</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Amount, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Amount)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-primary" id="saveAccountButton">Save</button>
                        @*<button type="button" class="btn btn-primary">Done</button>*@
                        @Html.ActionLink("Done", "Index", null, new { @class = "btn btn-primary" })
                        @Html.ActionLink("Cancel", "Index", null, new{@class="btn btn-primary"})
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<script src="~/Scripts/account-edit.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/FinancialPlannerAccount/EditTransaction.cshtml
@using FinancialPlannerApplication.Extensions
@model FinancialPlannerApplication.Models.ViewModels.EditTransactionViewModel

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-8">
        <div class="form-horizontal">
            @using (Html.BeginForm(null, null, FormMethod.Post, new{@id="editTransactionForm"}))
            {
                @Html.HiddenFor(m => m.AccountTransactionId)
                @Html.HiddenFor(m => m.NewTransaction)
                @Html.HiddenFor(m => m.OldAccountId)
                @Html.HiddenFor(m => m.WasWithdrawal)
                @Html.HiddenFor(m => m.OldAmount)
                @Html.HiddenFor(m => m.FindingBudgetItems)
                
                @Html.ValidationSummary(true)
                <div class="form-group">
                    <label class="col-md-2 control-label">Name</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Amount</label>
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Amount, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.Amount)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Payment Date</label>
                    <div class="col-md-10">
                        @Html.EditorFor(m => m.PaymentDate, "Date", new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.PaymentDate)
                    </div>
                </div>
                if (Model.Accounts != null && Model.Accounts.Any())
                {
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Account
                        </label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(m => m.SelectedAccountId, Model.Accounts.ToSelectList(m => m.Name, m => m.Id, Model.Accounts.Where(m => m.Id == Model.SelectedAccountId), "--Select One--"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.SelectedAccountId)
                        </div>
                    </div>
                }
                if (Model.Expenses != null && Model.Expenses.Any())
                {
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Expense
                        </label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(m => m.SelectedExpenseId, Model.Expenses.ToSelectList(m => m.Name, m => m.Id, Model.Expenses.Where(m => m.Id == Model.SelectedExpenseId), "--Select One--"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.SelectedExpenseId)
                        </div>
                    </div>
                }

                if (Model.Budgets != null && Model.Budgets.Any())
                {
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Budget
                        </label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(m => m.SelectedBudgetId, Model.Budgets.ToSelectList(m => m.Name, m => m.Id, Model.Budgets.Where(m => m.Id == Model.SelectedBudgetId), "--Select One--"), new {@class = "form-control"})
                            @Html.ValidationMessageFor(m => m.SelectedBudgetId)
                        </div>
                    </div>
                }
                if (Model.BudgetItems != null && Model.BudgetItems.Any())
                {
                    <div class="form-group">
                        <label class="col-md-2 control-label">
                            Budget Item
                        </label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(m => m.SelectedBudgetItemId, Model.BudgetItems.ToSelectList(m => m.Name, m => m.Id, Model.BudgetItems.Where(m => m.Id == Model.SelectedBudgetItemId), "--Select One--"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.SelectedBudgetItemId)
                        </div>
                    </div>
                }
                <div class="form-group">
                    <div class="col-md-12">
                        <label class="col-md-2 control-label">Withdrawal</label>
                        <div class="col-md-2">
                            @Html.RadioButtonFor(m => m.IsWithdrawal, true)
                        </div>
                        <label class="col-md-2 control-label">Deposit</label>
                        <div class="col-md-4">
                            @Html.RadioButtonFor(m => m.IsWithdrawal, false)
                        </div>
                        @Html.ValidationMessageFor(m => m.IsWithdrawal)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-primary" id="saveAccountTransactionButton">Save</button>
                        <button type="button" class="btn btn-primary" id="doneEditAccountTransactionButton">Done</button>
                        @*@Html.ActionLink("Done", "Index", null, new { @class = "btn btn-primary" })*@
                        @Html.ActionLink("Cancel", "Index", null, new {@class = "btn btn-primary"})
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/Scripts/datepicker-initialize.js"></script>
<script src="~/Scripts/accountTransaction-edit.js"></script>

FinancialPlannerApplication/FinancialPlannerApplication/Views/FinancialPlannerAccount/Index.cshtml
@model FinancialPlannerApplication.Models.ViewModels.AccountIndexViewModel
@{
    ViewBag.Title = "Accounts";
}

@Html.HiddenFor(m => m.SelectedAccountId)

<div id="fpaIndex">
    <h2>
        Accounts
        <button class="btn btn-primary" id="addAccountButton" data-request-url="@Url.Action("AddAccount")">Add</button>
    </h2>

    <table class="table table-hover" id="accountsTable">
        <thead>
            <tr>
                <th>Name</th>
                <th>Amount</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var account in Model.Accounts)
            {
                <tr class="accountRow" id="@account.Id" data-request-url="@Url.Action("LoadAccountTransactions")">
                    <td>@account.Name</td>
                    <td>@account.Amount</td>
                    <td><button class="btn btn-primary editAccount" id="@account.Id" data-request-url="@Url.Action("EditAccount")">Edit</button></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div id="addAccount"></div>

<div id="editAccount"></div>

<div id="accountTransactions"></div>

@section scripts {
    <script src="~/Scripts/account-index.js"></script>
}